name: BuildTest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio
    - name: Run build test_esp8266 using PlatformIO
      run: pio test -e test_esp8266 -i test_07_pcf8574mux --without-testing --without-uploading
    - name: Run build test_esp32 using PlatformIO
      run: pio test -e test_esp32 -i test_07_pcf8574mux --without-testing --without-uploading
    - name: Run build spaiot_shield_pcf8574 using PlatformIO
      run: pio test -e spaiot_shield_pcf8574 -f test_07_pcf8574mux -f test_08_button -f test_09_framedecoder -f test_10_controlpanel  --without-testing --without-uploading
