name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # example: [examples/*/*]
        example: [examples/SpaSimple/SpaSimple, examples/SpaStatus/SpaStatus, examples/SpaSerialRemote/SpaSerialRemote, examples/SpaSerialRemoteI2c/SpaSerialRemoteI2c , examples/SpaHwCustom/SpaHwCustom, examples/SpaServerMqttClient/SpaServerMqttClient]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio
    - name: Step 6 - Run build examples using PlatformIO
      run: pio ci --lib="." -b esp12e -b esp32dev -b lolin_s3 -c examples/platformio.ini
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
