name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [examples/SpaSimple, examples/SpaStatus, examples/SpaSerialRemote, examples/SpaSerialRemoteI2c , examples/SpaHwCustom]

    steps:

    - name: Step 1 - Checkout Repo
      uses: actions/checkout@v2
    - name: Step 2 - Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Step 3 - Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Step 4 - Set up Python
      uses: actions/setup-python@v2
    - name: Step 5 - Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Step 6 - Run build examples using PlatformIO
      run: pio ci --lib="." -b esp12e -b esp32dev
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
    - name: Step 7 - Run build ESP8266 test using PlatformIO
      run: pio test -e ESP8266 --without-testing --without-uploading
    - name: Step 8 - Run build ESP32 test using PlatformIO
      run: pio test -e ESP32 --without-testing --without-uploading
