name: UnitTest

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build and test environment'     
        required: true
        default: 'esp32' 
        type: choice
        options:
        - esp32
        - esp8266

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Step 1 - Checkout Repo
      uses: actions/checkout@v2
    - name: Step 2 - Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Step 3 - Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Step 4 - Set up Python
      uses: actions/setup-python@v2
    - name: Step 5 - Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Step 6 - Run tests on the embedded target
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
        PLATFORMIO_DEFAULT_ENVS: ${{ github.event.inputs.environment }}
      run: platformio remote test -v
